// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type Expense struct {
	ID          int32
	UserID      int32
	Description string
	Amount      string
	CreatedAt   sql.NullTime
}

type User struct {
	ID       int32
	Username string
	Password string
}
